[package]
name = "neutron-sdk"
description = "Neutron CosmWasm SDK for interacting with Neutron blockchain"
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron-org/neutron-sdk"
homepage = "https://neutron.org"
readme = "README.md"

[dependencies]
cosmwasm-std = { workspace = true }
cosmos-sdk-proto = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
serde-json-wasm = { workspace = true }
bech32 = { workspace = true }
thiserror = { workspace = true }
protobuf = { workspace = true }
cosmwasm-schema = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
prost-types = { workspace = true }
hex = { workspace = true }
